# Generated by Django 4.1.4 on 2022-12-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
