# Generated by Django 4.1.4 on 2022-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_machine_image_url_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/machines'),
        ),
    ]
