# Generated by Django 4.1.4 on 2022-12-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='detailed_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
