# Generated by Django 4.1.4 on 2022-12-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0004_stock_description'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=12, null=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spares.sparepart'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='orders.order'),
            preserve_default=False,
        ),
    ]
