# Generated by Django 4.1.4 on 2022-12-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_remove_ordereditem_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='part_number',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
