# Generated by Django 4.1.4 on 2022-12-16 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_id_cart_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
