# Generated by Django 4.1.4 on 2022-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='description',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
