# Generated by Django 4.1.4 on 2022-12-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordereditem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
