# Generated by Django 4.1.4 on 2022-12-11 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('part_number', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{4}\\.\\d{4}$', message='Part number must be in the format xx.xxxx.xxxx')])),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
