# Generated by Django 4.1.4 on 2022-12-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='part_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spares.sparepart'),
        ),
    ]
