# Generated by Django 4.1.4 on 2022-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0003_alter_stock_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
