# Generated by Django 4.1.4 on 2022-12-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0005_alter_sparepart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
