# Generated by Django 4.1.4 on 2022-12-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0006_alter_sparepart_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='image_url',
            new_name='image',
        ),
    ]
